import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<nav className="bg-white shadow-md py-4 px-6 flex justify-between items-center">
  <a href="/" className="flex items-center space-x-3">
    <Image
      src="/logo.png"
      alt="ALGI Nexa LLC Logo"
      width={140}
      height={60}
    />
<span className="font-bold text-blue-900 text-2xl tracking-wide">
  ALGI Nexa LLC
</span>
  </a>

  <div className="space-x-6">
    <a href="/" className="hover:text-blue-700">Home</a>
    <a href="/about" className="hover:text-blue-700">About</a>
    <a href="/contact" className="hover:text-blue-700">Contact</a>
  </div>
</nav>
        {children}
      </body>
    </html>
  );
}
